/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a org.freedesktop.DBus.ObjectManager -c OrgFreeDesktopDBusObjectManager -N xml/org.freedesktop.DBus.ObjectManager.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "org.freedesktop.DBus.ObjectManager.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class OrgFreeDesktopDBusObjectManager
 */
OrgFreeDesktopDBusObjectManager::OrgFreeDesktopDBusObjectManager(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

OrgFreeDesktopDBusObjectManager::~OrgFreeDesktopDBusObjectManager()
{
    // destructor
}

ObjectMap OrgFreeDesktopDBusObjectManager::GetManagedObjects()
{
    // handle method call org.freedesktop.DBus.ObjectManager.GetManagedObjects
    ObjectMap objects;
    QMetaObject::invokeMethod(parent(), "GetManagedObjects", Q_RETURN_ARG(ObjectMap, objects));
    return objects;
}

