/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a org.freedesktop.DBus.ObjectManager -c OrgFreeDesktopDBusObjectManager -N xml/org.freedesktop.DBus.ObjectManager.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_FREEDESKTOP_DBUS_OBJECTMANAGER_H
#define ORG_FREEDESKTOP_DBUS_OBJECTMANAGER_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "dbus_types.h"

QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.freedesktop.DBus.ObjectManager
 */
class OrgFreeDesktopDBusObjectManager: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.DBus.ObjectManager")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.DBus.ObjectManager\">\n"
"    <method name=\"GetManagedObjects\">\n"
"      <annotation value=\"ObjectMap\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"      <arg direction=\"out\" type=\"a{oa{sa{sv}}}\" name=\"objects\"/>\n"
"    </method>\n"
"    <signal name=\"InterfacesAdded\">\n"
"      <annotation value=\"InterfaceMap\" name=\"org.qtproject.QtDBus.QtTypeName.In1\"/>\n"
"      <arg type=\"o\" name=\"object\"/>\n"
"      <arg type=\"a{sa{sv}}\" name=\"interfaces\"/>\n"
"    </signal>\n"
"    <signal name=\"InterfacesRemoved\">\n"
"      <annotation value=\"InterfaceList\" name=\"org.qtproject.QtDBus.QtTypeName.In1\"/>\n"
"      <arg type=\"o\" name=\"object\"/>\n"
"      <arg type=\"as\" name=\"interfaces\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    OrgFreeDesktopDBusObjectManager(QObject *parent);
    virtual ~OrgFreeDesktopDBusObjectManager();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    ObjectMap GetManagedObjects();
Q_SIGNALS: // SIGNALS
    void InterfacesAdded(const QDBusObjectPath &object, InterfaceMap interfaces);
    void InterfacesRemoved(const QDBusObjectPath &object, const QStringList &interfaces);
};

#endif
