/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -p org.bluez.Adapter1 -c Adapter1 -i dbus_types.h -N xml/org.bluez.Adapter1.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "org.bluez.Adapter1.h"

/*
 * Implementation of interface class Adapter1
 */

Adapter1::Adapter1(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

Adapter1::~Adapter1()
{
}

